apiVersion: v1
kind: Pod
metadata:
  name: dind
  labels:
    app: dind
spec:
  volumes:
    - name: dind-storage
      emptyDir: {}
  containers:
    - name: dind
      image: docker:dind
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
